figure('name','Module de Young Lignes verticales','NumberTitle','off')
for i = 1:10
    stem(i,Traction.Line(i).YoungM/(10^(9)), 'LineWidth', 1.5)
    hold on
end

xlim([0.5 10.5]);
title('Module de Young des échantillons de pistes horizontales en traction')
xlabel('N° échantillon');
ylabel('Module de Young (GPa)');
legend( 'clean', ...
        '1 ligne', ...
        '2 lignes', ...
        '3 lignes', ...
        '4 lignes', ...
        '5 lignes', ...
        '6 lignes', ...
        '7 lignes', ...
        'Plan de masse plein', ...
        'Plan de masse hachuré', ...
        'Location','northwest')

% figure('name','Traction Lignes verticales','NumberTitle','off')
% for i = 1:10
%     stem(i,Traction.Line(i).Pente, 'LineWidth', 1.5)
%     hold on
% end
% 
% xlim([0.5 10.5]);
% title('Pente de charge des échantillons de pistes horizontales en traction')
% legend( 'clean', ...
%         '1 ligne', ...
%         '2 lignes', ...
%         '3 lignes', ...
%         '4 lignes', ...
%         '5 lignes', ...
%         '6 lignes', ...
%         '7 lignes', ...
%         'Plan de masse plein', ...
%         'Plan de masse hachuré', ...
%         'Location','northwest')
    
% figure
% for i = 1:10
%     eval(sprintf('A = max(Traction.Line(%d).load);',i));
%     LoadMax(i) = A;
%     stem(i,LoadMax(i), 'LineWidth',1.5)
%     hold on
% end
% 
% xlim([0.5 10.5]);
% title('Charge maximum atteinte pour les échantillons pistes horizontales en traction')
% legend( 'clean', ...
%         '1 ligne', ...
%         '2 lignes', ...
%         '3 lignes', ...
%         '4 lignes', ...
%         '5 lignes', ...
%         '6 lignes', ...
%         '7 lignes', ...
%         'Plan de masse plein', ...
%         'Plan de masse hachuré', ...
%         'Location','northwest')
    
clear A i LoadMax